import "./App.css";
import ghIcon from "./assets/github-icon.png";
import icon from "./assets/ai.png";
import { useState } from "react";
import axios from "axios";
const apiURL = "https://openai-jpd3.onrender.com/";

function App() {
  const [prompt, setPrompt] = useState("");
  const [imageLoading, setImageLoading] = useState(false);

  const [result, setResult] = useState("");
  const generateImage = async (e) => {
    e.preventDefault();
    setResult("");
    setImageLoading(true);
    const res = await axios
      .get(`${apiURL}api/search?q=${prompt}`)
      .then((res) => setResult(res.data.result));
    setImageLoading(false);
  };

  return (
    <div className="app-main">
      <>
        <header>
          <img className="icon" src={icon} alt="" />
          <div className="title">
            <h2>Generate an Image using AI</h2>
            <h4>
              This app is created thanks to the OpenAI{" "}
              <a
                href="https://openai.com/blog/dall-e/"
                target="_blank"
                rel="noopener noreferrer"
              >
                DALL·E model
              </a>{" "}
            </h4>
          </div>
        </header>

        <form onSubmit={generateImage}>
          <textarea
            className="app-input"
            placeholder="Type a description that explains what image should be generated by AI..."
            onChange={(e) => setPrompt(e.target.value)}
            rows="5"
            cols="40"
            required
          />

          <button type="submit">
            {imageLoading ? "Image is loading..." : "Generate an image"}
          </button>
        </form>

        {result.length > 0 ? (
          <img
            loading="lazy"
            className="result-image"
            src={result}
            alt="result"
          />
        ) : (
          <></>
        )}
        <footer>
          <p>
            Made with ☕ in Warsaw |{" "}
            <a
              href="https://github.com/mateusz0909/AI-image-generator"
              target="_blank"
              style={{ display: "flex" }}
            >
              <span
                style={{
                  marginLeft: "0.3em",
                  marginRight: "0.3em",
                  height: "1.5em",
                }}
              >
                <img src={ghIcon} className="gh-logo"></img>
              </span>
            </a>{" "}
            mateusz0909
          </p>
        </footer>
      </>
    </div>
  );
}

export default App;
